export const auditActions = {
  leadCreated: "lead.created",
  leadQualified: "lead.qualified",
  statusChanged: "lead.status_changed",
  leadIncomplete: "lead.incomplete",
  humanReviewCreated: "human_review.created",
  quoteGenerated: "quote.generated",
  quoteSent: "quote.sent",
  followupScheduled: "followup.scheduled",
  followupSent: "followup.sent",
  modelRunCreated: "model_run.created",
  distanceResolved: "distance.resolved",
  validationError: "validation.error",
  agentError: "agent.error",
  promptInjectionDetected: "security.prompt_injection_detected",
  clientCreated: "client.created",
  clientUpdated: "client.updated",
  clientDeactivated: "client.deactivated",
  clientReactivated: "client.reactivated",
  clientDeleted: "client.deleted",
  unauthorizedAccess: "security.unauthorized_access"
} as const;
